# Key Concepts and Principles {#keys}

Before we get started, we need to discuss some basic ideas around data and their management.  Understanding these concepts and why they're important will facilitate the development and curation of open data for both you and others to use.  We start with general concepts and then dive into some detailed concepts.  The detailed concepts may seem daunting, but they are critical in supporting your journey in managing your own data.

## General concepts

### Data types and identifying important contributions

We briefly introduced a general concept of data in section \@ref(dataimp).  Throughout this document, we use the term "data" to describe a variety of products either directly supporting decision-making processes or used for research to support the former.  Data can be generated to support or refute hypotheses in research, whereas research can also produce data products that support environmental management.  The end game in all of these processes is understanding that data can be present at any stage in research and/or decisions that support environmental management.  Individuals may generally use the term "data" to describe products at any point in this workflow.  Understanding the diferent ways we talk about data will allow you to more carefully identify your data management needs.    

Identifying the types of data that are important to support decision-making is the first task in developing a data management workflow.  Any research project could produce countless datasets and it may be challenging to understand which datasets are important or are merely intermediate steps in a larger process.  To help you identify which datasets are important to your project, ask these questions:

1. What is the most important and tangible contribution of this project?  
1. Who is going to benefit from the results of this project? 
1. How can I use data management practices to make the use of these data "easier" for decision-making?

Answers to these questions can help you identify important data products that need formal data management workflows.  However, coming to a single answer is the exception, not the norm, and a typical answer usually is "it depends".  Also realize that you may be the direct beneficiary of a particular research project - documenting and using proper data management workflows will save you from headaches in the future.  Evaluating these questions at different steps throughout a project can help you identify the valuable contributions. 

In a perfect world where we have endless time and resources, and not to mention interest, to dedicate to data management, we would track and document the provenance of every single dataset used by a research project.  Of course, this is impractical, nor do we need to curate every piece of data.  You will need to identify the most important contribution of a project among alternatives based on your answers to the above questions.  Here are a couple scenarios that can help in this process. 

> I am collecting field data and/or running experiments in a laboratory.

The field or experimental data are obvious candidates for developing a data management workflow, yet it is rarely a solitary dataset that is produced.  Working with these data continuously throughout a project will benefit from developing a data dictionary and understanding linking keys between different data tables.  If you don't want or need to archive all the datasets you've used or created, identify a master dataset that provides the main results for your study.

> I am using data from an external source as primary or secondary information to support analysis or generate a reporting product

A derived dataset may be the most important contribution of this project.  This dataset includes multiple combinations of input datasets from external sources.  It is important to document the steps that were used to develop this dataset, including the raw sources of information and where they can be accessed.  Documentation can range from a general description of the dataset (less desirable) to complete access to source code for reproducing the derived dataset (more desirable).  The most important contribution may be the workflow or the derived dataset, depending on "who" can benefit most from this project. 

> I am producing a model to support scenario exploration or understanding of natural processes

Tracking data provenance of a modelling project is a challenging task simply because a "model" does not conform to the conventional understanding of data.  As noted above, we describe data as anything that can support decision-making in environmental management.  Models are commonly used for this task, yet understanding of their information content over time often rests with one individual, giving that modeller a very high bus factor.  There are practical limitations for fully tracking a model as a data product (e.g., computational limits, time requirements, required knowledge of its working components), but there are certainly derived datasets from models that can benefit from data management.  In particular, model results, parameters, or source code are all prime candidates for data management, depending on the audience. 

> I am developing a decision-support tool 

Related to the challenges of data management for modelling, so-called "decision-support" tools are increasingly used as a front-end for decision-makers to access relevant information from a research project or intensive data collection effort. Online interactive dashboards have proliferated tremendously in the last ten years to meet this need.  These tools can be useful in the right hands, yet there is no community standard for how to treat these products as data to track their origin and metadata.  In this case, documenting the workflow, source code, and requisite datasets for powering the dashboard may be the most important contributions.

### The FAIR principles

The previous section presented several questions to ask yourself that can aid in identifying important contributions of a research project as a focus for data management.  In all cases, once that important contribution is identified, community standards or best practices for that dataset or product should be used to ensure the intended audience can find, access, use, and replicate the data.  The FAIR principles [@Wilkinson16] provide some general guidelines to follow for ensuring the openness of a data product.  The FAIR acronym is described as follows:

* **F**indable: The data have a globally unique and persistent identifier, including use of "rich" metadata.
* **A**ccessible: Once found, the data can be retrieved using standardized communications protocols that are open, free, and universally implementable.
* **I**interoperable: The ability of data or tools from non-cooperating resources to integrate or work together with minimal effort.
* **R**eusable: If the above are achieved, the data and metadata are described in a way that they can be replicated and/or combined in different settings.  

What this means simply is that 1) each dataset has a name that doesn't change and can be found with minimal effort using that name, 2) once it's found, you can actually get your hands on it (e.g., not behind a paywall), 3) once you have it, you can use readily available tools to work with the data (e.g., not using proprietary software), and 4) you can actually apply the data for your own needs because it has sufficient context, including its reproduction, given the the first three principles are met.  

In practice, the FAIR principles invoke several concepts that will be described in detail later, but we describe some here as a gentle introduction.  The term "globally unique and persistent identifier" (under **F**) is a mouthful that simply means the dataset has a name assigned to itself that is not assigned to any other dataset (globally unique) and it's permanent (persistent).  This doesn't mean a descriptive or literal name, such as you would assign to a file on your own computer, rather it means a computer-generated identifier created using a known standard.  One such example is a [DOI](https://www.doi.org/), or digital object identifier.  These are commonly assigned to publications as a static web address (unique and persistent) and are increasingly being used as identifiers for datasets.  

Findable and accessible also imply the data have a home with an address.  The latter describes the unique identifier, whereas the home itself is permanent location as a requirement for accessibility.  There are several options for where data can live long-term and theoretically forever so long as the internet exists.  There are literally thousands of repositories online that can be used for data archival and the answer to which repository you should use is almost always going to be "it depends".  We provide some examples in section \@ref(tools) as one option used by TBEP.

The FAIR principles are not rigorous standards, rather they establish general questions you should ask of a dataset to make sure you've done your due diligence in achieving openness.  Further, because they are not rigorously defined, different organizations may interpret the principles differently and it's important to realize that your understanding of the principles may differ from others.  For example, individuals may define "reusable" in different ways that can affect the level of detail provided in the metadata. These principles are presented here as a reminder to think about them often, especially during the beginning of a project, and how they can be applied in opening the most important contribution of your project. 

## Specific concepts

* Types of data products (e.g., raw data, models, synthesized/derived data, etc.) or types of data (flat file, spatial, disparate)
* Tabular data
     * an overview of tidy data, can a machine read it? 
     * The wrong approach
 * Basic database principles
     * logical extension of tidy data
     * normalized tables (including discussion of key variables), what are unique ids (e.g., tberf oyster, how did I make the unique id?), facilitate standard DB queries
* Metadata principles

### Metadata 

Just as "data" can have different meanings to different people, "metadata" is a loosely defined term that describes one of the most important aspects of data management.  Metadata varies from simple text descriptions of a dataset, such as "who", "what", "when", "where", "why", and "how", to more formalized standards with the intent of preparing your data for archival in a long-term repository.  Having no metadata is almost a guarantee that your dataset will be orphaned or misused by others, either inadvertently or with willful acknowledgment that the original purpose of the data is unknown and its use may be inappropriate for the task at hand.  Metadata are also important for enabling discovery of your data (the __F__ in FAIR).  So, when you think of data management, you should think of it as being synonymous with metadata curation. 

At its basic level, metadata is literally defined as "data about data" or "information about information" as en even more generalized definition.  A more comprehensive definition is provided by @Gilliland16:  

> A suite of industry or disciplinary standards as well as additional internal and external documentation and other data necessary for the identification, representation, interoperability, technical management, performance, and use of data contained in an information system

We use this definition as a starting point to develop our thinking around best practices for metadata generation and curation.  Again, it's good to emphasize that some metadata is better than no metadata.  Just because you are not using industry or disciplinary standards for generating metadata doesn't mean you're approach is incorrect.  As you get comfortable with the general purpose of metadata and how it's developed as a description for a dataset, you can build on this knowledge by adopting more formalized standards for developing metadata.   

At its basic level, think of metadata as a simple text file containing the information about your dataset. This text file provides answers to common questions about the origin of your data so that anyone (or a computer) with zero knowledge about your data can quickly orient themselves as to its purpose.  The US Geological Survey provides a useful document on creating [Metadata in "plain language"](https://prd-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/atoms/files/Metadata%20in%20Plain%20Language_508compliant.pdf) to distill the basic information contained in a metadata file.  As indicated above, it provides a workflow for answering the "who", "what", "when", "where", "why", and "how" questions for metadata.  We provide a brief synopsis of these questions below. You can use this workflow to generate your own metadata.

> What does the dataset describe?

Information here would include very basic details about the dataset including a **title**, **geographic extent**, and **period of time** covered by the data.  For geographic extent, this may often include explicit coordinates covering the study area, i.e., the lower left and upper right of a bounding box.  Location is useful for indexing your dataset relative to others, if for example, a researcher wanted to find data for all studies in the geographic extent of Tampa Bay. Other useful information about the "what" might include the type of data, e.g., tabular, map, online dashboard, etc. 

> Who produced the dataset? 

This would be yourself and anyone else who has made a significant contribution to the development of a dataset.  People may have differing opinions regarding what defines a "significant" contribution, but as the curator of a dataset, it's up to you to determine how important it is for including an individual as a contributor.  Data are increasingly being used as citable reseources and including individuals that were important in its generation ensures proper attribution.  For scientific publications, each author is generally expected to have made substantial contributions to the study conception and design, data acquisition or analysis, or interpretation of results.  The same would apply to data.  If someone has spent hours toiling in the field to collect the data or hours visually scanning a spreadsheet for quality control, include them!

> why was the dataset created? 

Describing why a dataset was created is critically important for developing context.  If others want to use your data, they need to know if its appropriate for their needs.  Here you would describe the goal or objectives of the research for which the data were collected.  It should be clear if there are limitations in your data defined by your goals, if for example, you collect field data in a particular season to address temporal questions.  Using these data to answer broader temporal questions, such as inter-annual changes, would not be inappropriate and could lead to wrong conclusions.  Identifying the "why" of your dataset could also prevent misinterpretation or misuse of the data by non-specialists.  Think of it as an insurance policy for your data.

> How was the dataset created? 

Here you would describe the methods used to generate the data, e.g., field sampling techniques, laboratory methods, etc.  This information is important so others can know if you've used proper and accepted methods for generating the data.  Citing existing SOPs or methods that are recognized standards in your field would be appropriate.  If you are generating a synthesis data product using data from external sources, make sure to document where those data come from and the methods you used for synthesis.  Pay attention to documenting the software that was used, including the version numbers.  If you have analysis code or script that was used for synthesis, provide a link if possible.   

> How reliable are the data? 

It's also very important to document aspects of a dataset that affect reliability.  The answers you provide to the above questions can provide context to this reliability, but it's also imporant to explicitly note instances when the data could be questionable or inappropriate to use.  Here you could describe any quality assurance or quality control (QAQC) checks that were used on the data.  There are often formalized ways to do so, such as codes or descriptors in tabular data defining QAQC values (e.g., data in range, below detection, sensor out of service, etc.).  You will want to clearly describe what each of these codes mean and if they cover the range of conditions possible for your data.  Other QAQC procedures, such as how the data were verified for accuracy, can also be described.   

> How can someone get a copy of the dataset?

Good metadata always has information on who has the data and how to contact them for requesting access.  For archived or publicly available data, this information is more important for who to contact should you have questions.  Information on obtaining a copy of the data should also describe any special software or licensing issues related to accessing the data.  Under the **I** in FAIR, you should strive to make your data as interoperable as possible and not store your data in an obscure format that requires specialized software.  If this is unavoidable (e.g., your data are large and its need to be compressed), describe what needs to be done to access the data.  Any licensing or permissions issues on using data should also be described, e.g., is it free for use with or without attribution, are there limitations on its use, etc. There's a lot to say about licensing  


     * Minimum requirements - seagrass desoto buoy example
     * Formal standards, https://nceas.github.io/oss-lessons/ecological-metadata/ecological-metadata.html
     * data dictionaries, naming conventions

* Best practices for QA

* Where do data live long-term, what's a doi, considering a data paper, federated repository, etc.
     * The A in FAIR
     * GitHub repository
     * Stable URL
     * Official repository
